[project]
name = "hibp"
version = "0.1.0"
dependencies = [
    "requests",
    "python-dotenv",
    "pydantic",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"